// app/api/chat/route.ts

import { streamText } from 'ai'
import { createOpenAICompatible } from '@ai-sdk/openai-compatible'

const alibaba = createOpenAICompatible({
  apiKey: process.env.ALIBABA_API_KEY!,
  baseURL: 'https://dashscope-intl.aliyuncs.com/compatible-mode/v1'
})

export async function POST(req: Request) {
  // Extract the `messages` from the body of the request
  const { messages } = await req.json();

  // Get a language model
  const model = alibaba('qwen3-max-preview')

  // Call the language model with the prompt
  const result = streamText({
    model,
    messages,
    maxTokens: 16384,
    temperature: 0.7,
    topP: 1,
  })

  // Respond with a streaming response
  return result.toAIStreamResponse()
}
blank_issues_enabled: false
